

#include "STD_TYPES.h"
#include "PCINT_cfg.h"

const PCINT_cfg PCINT_cfgArr[25]=
{
	{PCINT_0,ON},
	{PCINT_1,ON},
	{PCINT_2,ON},
	{PCINT_3,ON},
	{PCINT_4,ON},
	{PCINT_5,ON},
	{PCINT_6,OFF},
	{PCINT_7,OFF},
	{PCINT_8,OFF},
	{PCINT_9,OFF},
	{PCINT_10,OFF},
	{PCINT_11,OFF},
	{PCINT_12,OFF},
	{PCINT_13,OFF},
	{PCINT_14,OFF},
	{Resv,OFF},
	{PCINT_15,OFF},
	{PCINT_16,OFF},
	{PCINT_17,OFF},
	{PCINT_18,OFF},
	{PCINT_19,OFF},
	{PCINT_20,OFF},
	{PCINT_21,OFF},
	{PCINT_22,OFF},
	{PCINT_23,OFF}
};
